### ISSUE TITLE
SwiftUI 컴포넌트 배우기

### ISSUE THREAD

**Issue by minnnidev** [IN-SOPT-KingofSwiftUI/MIN#2]
### 🍎 이슈 요약
인프런 한 조각씩 배우는 SwiftUI - 입문편의 SwiftUI 컴포넌트 배우기

### 🍏 ToDo
- [x] 눌러서 쓰는 Button 사용해 보기
- [x] 글자를 보여주는 Text 사용해 보기
- [x] Image 추가해 보기
- [x] Stack 이용해 보기
- [x] ScrollView 사용해 보기
- [x] List 사용해 보기
- [x] Section 이해
- [x] 컴포넌트 사이의 공간을 만들어주는 Spacer
- [x] Color
